# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 获取系统时间

on:
    workflow_dispatch:
    schedule:
        #- cron: "0,20 0,5,19 * * *"
        - cron: "0 0 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_joy

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: |
                  npm install
                  npm i silly-datetime 
            - name: "【获取系统时间】"
              run: |
                  node gettime.js
              env:
                  JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }}
                  JD_DEBUG: ${{ github.event.client_payload.JD_DEBUG || secrets.JD_DEBUG }}
                  JD_USER_AGENT: ${{ github.event.client_payload.JD_USER_AGENT || secrets.JD_USER_AGENT }}
                  PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }}
                  BARK_SOUND: ${{ github.event.client_payload.BARK_SOUND || secrets.BARK_SOUND }}
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
                  DD_BOT_TOKEN: ${{ github.event.client_payload.DD_BOT_TOKEN || secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ github.event.client_payload.DD_BOT_SECRET || secrets.DD_BOT_SECRET }}
                  IGOT_PUSH_KEY: ${{ github.event.client_payload.IGOT_PUSH_KEY || secrets.IGOT_PUSH_KEY }}
                  QQ_SKEY: ${{ github.event.client_payload.QQ_SKEY || secrets.QQ_SKEY }}
                  QQ_MODE: ${{ github.event.client_payload.QQ_MODE || secrets.QQ_MODE }}
                  QYWX_KEY: ${{ github.event.client_payload.QYWX_KEY || secrets.QYWX_KEY }}
                  QYWX_AM: ${{ github.event.client_payload.QYWX_AM || secrets.QYWX_AM }}
                  PUSH_PLUS_TOKEN: ${{ github.event.client_payload.PUSH_PLUS_TOKEN || secrets.PUSH_PLUS_TOKEN }}
                  PUSH_PLUS_USER: ${{ github.event.client_payload.PUSH_PLUS_USER || secrets.PUSH_PLUS_USER }}
                  JOY_FEED_COUNT: ${{ github.event.client_payload.JOY_FEED_COUNT || secrets.JOY_FEED_COUNT }}
                  JOY_RUN_FLAG: ${{ github.event.client_payload.JOY_RUN_FLAG || secrets.JOY_RUN_FLAG }}
                  JOY_TEAM_LEVEL: ${{ github.event.client_payload.JOY_TEAM_LEVEL || secrets.JOY_TEAM_LEVEL }}
                  SYNCURL: https://raw.githubusercontent.com/307146114/cc_jd/master/jd_joy.js
                  
                  BOOKSHOP_SHARECODES: ${{ github.event.client_payload.BOOKSHOP_SHARECODES || secrets.BOOKSHOP_SHARECODES }}
                  DDFACTORY_SHARECODES: ${{ github.event.client_payload.DDFACTORY_SHARECODES || secrets.DDFACTORY_SHARECODES }}
                  DREAM_FACTORY_SHARE_CODES: ${{ github.event.client_payload.DREAM_FACTORY_SHARE_CODES || secrets.DREAM_FACTORY_SHARE_CODES }}
                  FRUITSHARECODES: ${{ github.event.client_payload.FRUITSHARECODES || secrets.FRUITSHARECODES }}
                  JDJOY_SHARECODES: ${{ github.event.client_payload.JDJOY_SHARECODES || secrets.JDJOY_SHARECODES }}
                  JDNIAN_SHARECODES: ${{ github.event.client_payload.JDNIAN_SHARECODES || secrets.JDNIAN_SHARECODES }}
                  JDSXSY_SHARECODES: ${{ github.event.client_payload.JDSXSY_SHARECODES || secrets.JDSXSY_SHARECODES }}
                  JD_CASH_SHARECODES: ${{ github.event.client_payload.JD_CASH_SHARECODES || secrets.JD_CASH_SHARECODES }}
                  JD_JOY_REWARD_NAME: ${{ github.event.client_payload.JD_JOY_REWARD_NAME || secrets.JD_JOY_REWARD_NAME }}
                  JXNC_SHARECODES: ${{ github.event.client_payload.JXNC_SHARECODES || secrets.JXNC_SHARECODES }}
                  MARKET_COIN_TO_BEANS: ${{ github.event.client_payload.MARKET_COIN_TO_BEANS || secrets.MARKET_COIN_TO_BEANS }}
                  PETSHARECODES: ${{ github.event.client_payload.PETSHARECODES || secrets.PETSHARECODES }}
                  PLANT_BEAN_SHARECODES: ${{ github.event.client_payload.PLANT_BEAN_SHARECODES || secrets.PLANT_BEAN_SHARECODES }}
                  SUPERMARKET_LOTTERY: ${{ github.event.client_payload.SUPERMARKET_LOTTERY || secrets.SUPERMARKET_LOTTERY }}
